language: python
python:
  - "3.8.0"
install:
  - pip install -r requirements-dev.txt

jobs:
  include:
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        api_key:
          secure: d8c6a2a3-1ef7-4ff4-8b24-ec4913ec85a1
        app: gestao-clientes-senecti
        on: master
        run: "python manage.py migrate"
