language: python
python:
  - "3.8.0"
install:
  - pip install -r requirements-dev.txt

jobs:
  include:
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        api_key:
          secure: 6f48c95d-79c8-4c98-88da-d1541ee2a7db
        app: gestao-clientes-senecti
        on: master
        run: "python manage.py migrate"
