language: python
python:
  - "3.8.0"
install:
  - pip install -r requirements-dev.txt

jobs:
  include:
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        api_key: $SECRET_KEY_TRAVIS
        app: gestao-clientes-senecti
        on: master
        run: "python manage.py migrate"
