# Generated by Django 3.0.7 on 2020-07-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Document'),
        ),
    ]
